---
name: ntnn/docker-imapfilter changes

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-main:
    # This job builds an image from the current main branch in the
    # official repository.
    # The resulting image is tagged with main and latest.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          tags: ntnn/imapfilter:main,ntnn/imapfilter:latest
          # Only push when building main
          push: ${{ github.ref == 'refs/heads/main' }}
