---
name: ntnn/docker-imapfilter changes

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-main:
    # This job builds an image from the current main branch in the
    # official repository.
    # The resulting image is tagged with main and latest.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          repository: ntnn/imapfilter
          tags: main,latest
          # Only push when building main
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
